-- Add new RoleType enum values only
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'SENATOR';
